import { Injectable } from '@angular/core';
import { Listing } from './listing.model';

@Injectable({
  providedIn: 'root'
})
export class ListingService {
  private listings: Listing[] = [

    {
      "id": 1,
      "district": 5,
      "size": 75,
      "roomCount": "2+1",
      "buildingAge": "0-4",
      "floor": 2,
      "totalFloors": 6,
      "heating": "Doğalgaz",
      "bathroomCount": 1,
      "hasBalcony": true,
      "hasElevator": true,
      "hasParking": false,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Boş",
      "price": "3.050.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-basin-sitesi-yesilyurt-hast-yakini-deniz-manzarali-2-plus1-daireler-1158495875/detay"
    },
    {
      "id": 2,
      "district": 5,
      "size": 120,
      "roomCount": "3+1",
      "buildingAge": "0-4",
      "floor": 2,
      "totalFloors": 5,
      "heating": "Doğalgaz",
      "bathroomCount": 1,
      "hasBalcony": true,
      "hasElevator": true,
      "hasParking": true,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Boş",
      "price": "4.550.000 TL ",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-araphasan-mah-tapu-masrafsiz-otoparkli,asansorlu-sifir-daireler-1121971051/detay"
    },
    {
      "id": 3,
      "district": 5,
      "size": 80,
      "roomCount": "2+1",
      "buildingAge": "0-4",
      "floor": 4,
      "totalFloors": 7,
      "heating": "Doğalgaz",
      "bathroomCount": 1,
      "hasBalcony": true,
      "hasElevator": true,
      "hasParking": true,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Boş",
      "price": "2.700.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-cevreyolu-yakini-site-icinde-sifir-kira-getirisi-yuksek-2-plus1daire-1113820583/detay"
    },
    {
      "id": 4,
      "district": 5,
      "size": 135,
      "roomCount": "3+1",
      "buildingAge": "26-40",
      "floor": 6,
      "totalFloors": 8,
      "heating": "Doğalgaz",
      "bathroomCount": 1,
      "hasBalcony": true,
      "hasElevator": true,
      "hasParking": true,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Boş",
      "price": "4.345.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-isbey-den-inonu-caddesi-uzeri-metro-yakini-3-plus1-arakat-otoparkli-1151826859/detay"
    },
    {
      "id": 5,
      "district": 5,
      "size": 110,
      "roomCount": "2+1",
      "buildingAge": "0-4",
      "floor": 8,
      "totalFloors": 8,
      "heating": "Doğalgaz",
      "bathroomCount": 1,
      "hasBalcony": true,
      "hasElevator": true,
      "hasParking": false,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Kiracılı",
      "price": "4.500.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-fahrettin-altay-goztepe-stadi-yakini-satilik-2-plus1-1156612005/detay"
    },
    {
      "id": 6,
      "district": 5,
      "size": 130,
      "roomCount": "3+1",
      "buildingAge": "5-10",
      "floor": 1,
      "totalFloors": 4,
      "heating": "Doğalgaz",
      "bathroomCount": 2,
      "hasBalcony": true,
      "hasElevator": true,
      "hasParking": true,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Boş",
      "price": "2.650.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-esentepe-yeni-bina-otoparkli-ebeveyn-banyolu-3-plus1-satilik-daire-1141159848/detay"
    },
    {
      "id": 7,
      "district": 5,
      "size": 135,
      "roomCount": "3+1",
      "buildingAge": "26-40",
      "floor": 2,
      "totalFloors": 4,
      "heating": "Doğalgaz",
      "bathroomCount": 1,
      "hasBalcony": true,
      "hasElevator": false,
      "hasParking": true,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Boş",
      "price": "4.550.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-metroya-yurume-mesafesinde-komple-yenilenmis-3-plus1-satilik-daire-1147998908/detay"
    },
    {
      "id": 8,
      "district": 5,
      "size": 125,
      "roomCount": "3+1",
      "buildingAge": "16-25",
      "floor": 1,
      "totalFloors": 8,
      "heating": "Kombi",
      "bathroomCount": 1,
      "hasBalcony": true,
      "hasElevator": true,
      "hasParking": true,
      "isFurnished": false,
      "isInSite": true,
      "occupancyStatus": "Kiracılı",
      "price": "3.100.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-camlikent-sitesinde,ara-kat,asansorlu,otoparkli3-plus1,satilik-daire-1130060653/detay"
    },
    {
      "id": 9,
      "district": 5,
      "size": 135,
      "roomCount": "3+1",
      "buildingAge": "26-40",
      "floor": 1,
      "totalFloors": 4,
      "heating": "Doğalgaz",
      "bathroomCount": 1,
      "hasBalcony": true,
      "hasElevator": false,
      "hasParking": true,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Mülk Sahibi",
      "price": "2.950.000 TL ",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-emin-den-manolya-parki-manzarali-satilik-3-plus1-1158337257/detay"
    },
    {
      "id": 10,
      "district": 5,
      "size": 130,
      "roomCount": "3+1",
      "buildingAge": "5-10",
      "floor": 1,
      "totalFloors": 4,
      "heating": "Doğalgaz",
      "bathroomCount": 2,
      "hasBalcony": true,
      "hasElevator": true,
      "hasParking": true,
      "isFurnished": false,
      "isInSite": true,
      "occupancyStatus": "Mülk Sahibi",
      "price": "3.800.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-otobana-2-km-plussitede-plusebeveyn-plus-cift-cephe-plusotopark-plus3-balkon-1112901750/detay"
    },
    {
      "id": 11,
      "district": 5,
      "size": 145,
      "roomCount": "3+1",
      "buildingAge": "26-40",
      "floor": 1,
      "totalFloors": 4,
      "heating": "Doğalgaz",
      "bathroomCount": 1,
      "hasBalcony": true,
      "hasElevator": false,
      "hasParking": true,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Kiracılı",
      "price": "3.650.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-basin-sitesi,akevler-kavsagi-yakini,ara-kat,3-plus1,satilik-daire-1154837757/detay"
    },
    {
      "id": 12,
      "district": 5,
      "size": 100,
      "roomCount": "3+1",
      "buildingAge": "16-25",
      "floor": 3,
      "totalFloors": 7,
      "heating": "Doğalgaz",
      "bathroomCount": 1,
      "hasBalcony": true,
      "hasElevator": true,
      "hasParking": true,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Boş",
      "price": "3.300.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-istinye-avm-yakini-onu-acik-ferah-17-yasinda-3-plus1-satilik-kod805-1135778026/detay"
    },
    {
      "id": 13,
      "district": 5,
      "size": 85,
      "roomCount": "2+1",
      "buildingAge": "16-25",
      "floor": 1,
      "totalFloors": 5,
      "heating": "Doğalgaz",
      "bathroomCount": 1,
      "hasBalcony": true,
      "hasElevator": false,
      "hasParking": false,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Boş",
      "price": "1.775.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-gulyaka-mahallesinde-2-plus1-satilik-daire-1158236365/detay"
    },
    {
      "id": 14,
      "district": 5,
      "size": 110,
      "roomCount": "2+1",
      "buildingAge": "26-40",
      "floor": 1,
      "totalFloors": 3,
      "heating": "Klima",
      "bathroomCount": 1,
      "hasBalcony": true,
      "hasElevator": false,
      "hasParking": false,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Boş",
      "price": "2.650.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-bozyaka-merkezi-konumda-2-plus1-satilik-daire-1160773122/detay"
    },
    {
      "id": 15,
      "district": 5,
      "size": 150,
      "roomCount": "3+1",
      "buildingAge": "0-4",
      "floor": 3,
      "totalFloors": 6,
      "heating": "Doğalgaz",
      "bathroomCount": 2,
      "hasBalcony": true,
      "hasElevator": true,
      "hasParking": true,
      "isFurnished": false,
      "isInSite": false,
      "occupancyStatus": "Boş",
      "price": "5.350.000 TL",
      "link": "https://www.sahibinden.com/ilan/emlak-konut-satilik-ali-fuat-cebesoy-mah-satilik-3-plus1-genis-ferah-sifir-daireler-1160671462/detay"
    }
  ];

  constructor() { }

  getAllListings(): Listing[] {
    return [...this.listings];
  }

  getListingById(id: string): Listing | undefined {
    const numericId = Number(id); // Convert string id to number
    return this.listings.find(listing => listing.id === numericId);
  }
}
